# Generated by Django 5.1.2 on 2024-11-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_alter_titles_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='cover',
            field=models.ImageField(null=True, upload_to='./static/images'),
        ),
    ]
