# Generated by Django 5.1.2 on 2024-11-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_titles_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='cover',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
